model_name: convnext_large
model_type: dinov3_convnext
hub_id: facebook/dinov3-convnext-large-pretrain-lvd1689m

hidden_sizes: [192, 384, 768, 1536]
depths: [3, 3, 27, 3]

num_channels: 3
image_size: 224
hidden_act: gelu
layer_norm_eps: 1.0e-6
layer_scale_init_value: 1.0e-6
drop_path_rate: 0.0
initializer_range: 0.02
